build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/dockerfile-validator
  commands:
    - go get -u github.com/jstemmer/go-junit-report
    - go get github.com/docker/docker/builder/dockerfile/command
    - go get github.com/docker/docker/builder/dockerfile/parser
    - go get gopkg.in/yaml.v2
    - go get github.com/stretchr/testify/assert
    - go test -v | go-junit-report > report.xml
    - cat report.xml
    - ls -latrh
    - ./validate-dockerfile.sh
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/dockerfilevalidator
    storage_driver: vfs
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master

    branch: master


