apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dockerfilevalidator
    env: ci
  name: dockerfilevalidator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dockerfilevalidator
        image.base: scratch
        lang: go
    spec:
      containers:
      - image: quay.io/ukhomeofficedigital/dockerfilevalidator:latest
        name: dockerfilevalidator
        ports:
        - name: dockerfile
          containerPort: 8080





